apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-deployment
  ports:
  - nodePort: 30009
    port: 8080
    targetPort: 8080
  type: NodePort
