info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
    urlmapping:
      cache:
        maxsize: 1000
    controllers:
      defaultScope: singleton
      upload:
        # ~7GB
        maxFileSize: 7365197824
        maxRequestSize: 7365197824
    converters:
      encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  controllers:
    defaultScope: singleton

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  format_sql: true
  use_sql_comments: true

environments:
  production:
    dataSource:
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      pooled: true
      jmxExport: true
      dbCreate: update
      properties:
        maxActive: -1
        minEvictableIdleTimeMillis: 1800000
        timeBetweenEvictionRunsMillis: 1800000
        numTestsPerEvictionRun: 3
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        validationQuery: "SELECT 1"
        jdbcInterceptors: "ConnectionState"
  development:
    dataSource:
      url: jdbc:h2:./data/db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      pooled: true
      jmxExport: true
      dbCreate: update
      logSql: true
  test:
    dataSource:
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: ''
      pooled: true
      jmxExport: true
      dbCreate: create-drop
      logSql: true
